export const reportType = [
  "Crime",
  "Accident",
  "Hazards",
  "Arson/Fire",
  "Others",
];
export const severityLevels = ["Minor", "Moderate", "Severe"];

export const crimes = [
  "Robbery",
  "Murder",
  "Burglary",
  "Assault",
  "Fraud",
  "Vandalism",
  "Kidnapping",
  "Homicide",
  "Cybercrime",
  "Shoplifting",
  "Identity Theft",
  "Drug Trafficking",
  "Domestic Violence",
  "Carjacking",
  "Forgery",
  "Human Trafficking",
  "Embezzlement",
  "Harassment",
  "Public Intoxication",
];

export const murderTypes = [
  "Homicide",
  "Manslaughter",
  "Assassination",
  "Serial Killing",
  "Mass Murder",
  "Domestic Violence",
  "Gang-related Murder",
  "Robbery-related Murder",
  "Drug-related Murder",
  "Honor Killing",
  "Drive-by Shooting",
  "Child Abuse-related Murder",
];

export const locationOptions = ["Pantal"];

export const accidentTypes = [
  "Car accidents",
  "Motorcycle accidents",
  "Bicycle accidents",
  "Pedestrian accidents",
  "Slips, trips, and falls",
  "Machinery accidents",
  "Falling objects",
  "Electrical accidents",
  "Falls at home",
  "Burns",
  "Poisoning",
  "Choking",
  "Earthquakes",
  "Hurricanes",
  "Tornadoes",
  "Floods",
  "Sports injuries",
  "Water-related accidents",
  "Playground accidents",
  "Chemical spills",
  "Explosions",
  "Structural failures",
  "Public transportation accidents",
  "Accidents in public spaces",
  "Amusement park accidents",
  "Lightning strikes",
  "Animal attacks",
  "Helicopter accidents",
  "Drone accidents",
  "Boat accidents",
];

export const hazardList = [
  "Physical Hazards",
  "Chemical Hazards",
  "Biological Hazards",
  "Ergonomic Hazards",
  "Radiation Hazards",
  "Psychosocial Hazards",
  "Environmental Hazards",
  "Electrical Hazards",
  "Fire Hazards",
];

export const arsonFireTypes = [
  "Incendiary Fire",
  "Accidental Fire",
  "Electrical Fire",
  "Wildfire",
  "Arson for Profit",
  "Vehicle Arson",
  "Structure Fire",
  "Arson for Vandalism",
  "Arson for Revenge",
  "Arson for Hate Crimes",
  "Molotov Cocktail",
  "Spontaneous Combustion",
  "Gasoline Fire",
  "Industrial Fire",
  "Terrorist Arson",
  "Pyromania",
];
